// Generated by CoffeeScript 1.6.3
/*
    Tests for HTTP API 
    Test Framework: Mocha (http://visionmedia.github.io/mocha/)
    Assertions: Should (https://github.com/visionmedia/should.js/)
*/


(function() {
  var Api, api, cfg, should;

  Api = (require('../lib/api.js')).Api;

  cfg = require('../cfg/config.js');

  should = require('should');

  api = new Api(cfg);

  beforeEach(function() {});

  describe('API parseUrl - Parameter Parsing', function() {
    it('should not replace any characters in a single string.', function(done) {
      var parameters, parametersExpected, _parameters;
      _parameters = ['name'];
      parametersExpected = 'name';
      parameters = api.parseUrl(_parameters);
      parameters.should.eql(parametersExpected);
      return done();
    });
    it('should replace a single / in a string', function(done) {
      var parameters, parametersExpected, _parameters;
      _parameters = ['name/first'];
      parametersExpected = 'name.first';
      parameters = api.parseUrl(_parameters);
      parameters.should.eql(parametersExpected);
      return done();
    });
    return it('should replace a single / in a string', function(done) {
      var parameters, parametersExpected, _parameters;
      _parameters = ['name/first/initial'];
      parametersExpected = 'name.first.initial';
      parameters = api.parseUrl(_parameters);
      parameters.should.eql(parametersExpected);
      return done();
    });
  });

}).call(this);
