// Generated by CoffeeScript 1.4.0
(function() {
  var Api, Firebase, api, app, cfg, express, firebase;

  express = require('express');

  cfg = require('./cfg/config.js');

  Firebase = require('firebase');

  Api = (require('./lib/api.js')).Api;

  app = express();

  app.use(express.bodyParser());

  app.use(express.cookieParser());

  /* Controllers
  */


  firebase = new Firebase(cfg.FIREBASE);

  api = new Api(cfg);

  /* Routes
  */


  app.get('/v0/name', function(req, res) {
    var name;
    name = {
      first: "Brad",
      last: "Dickason"
    };
    return res.send(name);
  });

  app.get('/v0/email', function(req, res) {
    var email;
    email = {
      personal: "dickason@gmail.com",
      work: "brad@shapeways.com"
    };
    return res.send(email);
  });

  app.get('/v0/social', function(req, res) {
    var social;
    social = {
      facebook: null,
      instagram: "bdickason",
      twitter: "@bdickason",
      web: "bdickason.com"
    };
    return res.send(social);
  });

  app.get('/:version/*', function(req, res) {
    var parameters;
    console.log(req.params);
    parameters = api.parseUrl(req.params);
    return res.send(parameters);
  });

  app.get('/');

  /* Start the App
  */


  app.listen("" + cfg.PORT);

}).call(this);
