// Generated by CoffeeScript 1.6.3
(function() {
  var Api, Endpoint;

  Endpoint = require('rest-endpoint');

  module.exports = Api = (function() {
    function Api() {}

    Api.prototype.get = function(ctx) {
      var endpoint, key, version;
      console.log(ctx);
      version = ctx.params.version;
      key = ctx.params[0];
      endpoint = new Endpoint(version, key);
      return endpoint.get(function(data) {});
    };

    return Api;

  })();

}).call(this);
