// Generated by CoffeeScript 1.6.3
/* rest-endpoint - Model representing a single endpoint 
      -e.x. /email could contain :
              { personal: "dickason@gmail.com", work: "brad@shapeways.com"}
      -which would make /email/personal:
              "dickason@gmail.com"
*/


(function() {
  var Endpoint, model, request;

  request = require('superagent');

  model = require('model');

  module.exports = Endpoint = model('Endpoint').attr('version').attr('key').attr('url');

  Endpoint.prototype.get = function(callback) {
    var _this = this;
    console.log("Key: " + this.attrs.key);
    console.log("Version: " + this.attrs.version);
    console.log("Url: " + this.attrs.url);
    return request.get("" + this.attrs.url + "/" + this.attrs.version + "/" + this.attrs.key, function(err, res) {
      if (err) {
        return console.log("Error: " + err);
      } else {
        return callback(res.body);
      }
    });
  };

}).call(this);
