// Generated by CoffeeScript 1.6.3
(function() {
  var Endpoint, request;

  request = require('superagent');

  module.exports = Endpoint = (function() {
    function Endpoint(version, key) {
      this.version = version || 'v0';
      this.key = key || '';
      this.url_base = 'http://localhost:3000/api';
    }

    Endpoint.prototype.get = function(callback) {
      var _this = this;
      console.log("Key: " + this.key);
      console.log("Version: " + this.version);
      return request.get("" + this.url_base + "/" + this.version + "/" + this.key, function(err, res) {
        if (err) {
          return console.log("Error: " + err);
        } else {
          console.log(res.body);
          return callback(res.body);
        }
      });
    };

    return Endpoint;

  })();

}).call(this);
