// Generated by CoffeeScript 1.6.3
(function() {
  var Endpoint, model, request,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  request = require('superagent');

  model = require('model');

  module.exports = Endpoint = (function(_super) {
    __extends(Endpoint, _super);

    function Endpoint(url, version, key) {
      this.version = version || 'v0';
      this.key = key || '';
      this.url = url || 'http://localhost:3000/api';
    }

    Endpoint.prototype.get = function(callback) {
      var _this = this;
      console.log("Key: " + this.key);
      console.log("Version: " + this.version);
      return request.get("" + this.url + "/" + this.version + "/" + this.key, function(err, res) {
        if (err) {
          return console.log("Error: " + err);
        } else {
          return callback(res.body);
        }
      });
    };

    return Endpoint;

  })(model);

}).call(this);
