// Generated by CoffeeScript 1.4.0

/* my-data API
*/


(function() {
  var Api;

  exports.Api = Api = (function() {

    function Api(cfg) {
      this.cfg = cfg;
    }

    Api.prototype.parseUrl = function(params) {
      return params[0].replace(/\//g, '.');
    };

    return Api;

  })();

}).call(this);
