// Generated by CoffeeScript 1.6.3
/* Endpoint-View - View for RESTful API Endpoints
      -Handles info flowing from Model/Controller
      -Renders JSON as beautiful HTMLs
*/


(function() {
  var View;

  View = require('view');

}).call(this);
