// Generated by CoffeeScript 1.6.3
/* rest-api - Controller for calling a RESTful API
      -Makes requests to an API of your choosing
      -Retrieves Endpoints from the rest-endpoint data model
      -Can get, delete, update
*/


(function() {
  var Api, Endpoint, reactive,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Endpoint = require('rest-endpoint');

  reactive = require('reactive');

  module.exports = Api = (function() {
    function Api(hostname, port, prefix) {
      this.get = __bind(this.get, this);
      this.hostname = hostname || 'localhost';
      this.port = port || 3000;
      this.prefix = 'api';
      this.url = "http://" + this.hostname + ":" + this.port + "/" + this.prefix;
    }

    Api.prototype.get = function(ctx) {
      var endpoint, key, version;
      console.log(ctx);
      version = ctx.params.version;
      key = ctx.params[0];
      endpoint = new Endpoint({
        url: this.url,
        version: version,
        key: key
      });
      return endpoint.get(function(data) {
        var child, value, values, _results;
        console.log(data);
        values = document.querySelector('.values');
        reactive(values, endpoint);
        _results = [];
        for (key in data) {
          value = data[key];
          console.log("Key: " + key);
          console.log("Value: " + value);
          child = "<tr id='" + key + "'><td class='key'>" + key + "</td><td class='value'>" + value + "</td><td class='actions'>a1</td></tr>";
          _results.push(console.log(child));
        }
        return _results;
      });
    };

    return Api;

  })();

}).call(this);
