// Generated by CoffeeScript 1.6.3
/* boot - This is the core client application*/


(function() {
  var Api, api, page;

  page = require('page');

  Api = require('rest-api');

  api = new Api;

  console.log(api);

  /* Routes*/


  page('/', function(ctx) {
    console.log('Homepage');
    return console.log(ctx);
  });

  page('/:version/*', api.get);

  page('/logout', function(ctx) {
    return console.log('Logout');
  });

  page('*', function(ctx) {
    return console.log('404');
  });

  page();

}).call(this);
